yolo_model:

  config_file:
    name: yolov3-tiny_RoboSub18.cfg
  weight_file:
    name: yolov3-tiny_RoboSub18_100000.weights
  threshold:
    value: 0.1 # Leave small b/c the yolo_processor will handle thresholding
  detection_classes:
    names:
      - GFlap
      - Dice5
      - Dice6
      - Slots_Fruit
      - Slots_Big_Red
      - Roulette
      - Buy_Gold_Chip
